/**
 * Team role
 */
export type TeamRole = "owner" | "admin" | "agent";

/**
 * Team type
 */
export type TeamType = "free" | "premium";

export interface TeamCode {
    /**
     * Code
     */
    code: string;
    /**
     * Code type. Custom is user provided
     */
    type: "autogenerated" | "custom";
}

export interface TeamBillingInfo {
    /**
     * Team billing email
     */
    billingEmail: string;
    /**
     * Last 4 digits for assigned card
     */
    cardDigits?: string | null;
}

/**
 * Team role -> member mapping
 */
export interface TeamMemberInfo {
    /**
     * Team id
     */
    teamId: number;
    /**
     * Member id
     */
    memberId: number;
    /**
     * Team role
     */
    role: TeamRole;
}

export interface TeamBlacklist {
    /**
     * Blacklist value type
     */
    type: "email";
    /**
     * Blacklist value
     */
    value: string;
}

/**
 * Basic team information
 */
export interface UserTeamInfo {
    /**
     * Team id
     */
    id: number;
    /**
     * Team name
     */
    name: string;
    /**
     * Team code
     * @deprecated Use codes instead
     */
    code: string;
    /**
     * Team codes
     */
    codes: TeamCode[];
    /**
     * Team role
     */
    role: TeamRole;

    /**
     * Team type
     */
    type: TeamType;

    /**
     * Premium renewal enable
     */
    premiumRenewalEnabled: boolean;

    /**
     * Premium expiration date when team type is premium
     */
    premiumExpiration?: string;

    /**
     * Team billing information. May be undefined if not assigned
     */
    billingInfo?: TeamBillingInfo;

    /**
     * Team blacklist if set
     */
    blacklist: TeamBlacklist[];
}
