import { ActionDescriptor } from "../../../common/realtimeAction";
import {
    ADD_TEAM_CODE,
    CHANGE_TEAM_NAME,
    CHECK_TEAM_CODE,
    CREATE_TEAM,
    DELETE_TEAM,
    DELETE_TEAM_CODE,
    GET_TEAM,
    LEAVE_TEAM,
    SET_TEAM_DND,
    UPDATE_BLACKLIST,
    UPDATE_TEAM_SETTINGS,
} from "../../constants/team";
import { BasicUserInformation } from "../user";
import { FullTeamInfo, TeamSettings } from "./interfaces";

export type GetTeamAction = ActionDescriptor<typeof GET_TEAM,
    {
        /**
         * Team id
         */
        id: number;
    }, {
        team: FullTeamInfo;
        /**
         * Team/team invite members
         */
        members: BasicUserInformation[];
    }>;

/**
 * Set team DND flag for requested user
 */
export type SetTeamDNDAction = ActionDescriptor<typeof SET_TEAM_DND,
    {
        /**
         * Team id
         */
        id: number;
        /**
         * DND flag
         */
        dnd: boolean;
    }, {}>;

export type DeleteTeamAction = ActionDescriptor<typeof DELETE_TEAM,
    {
        /**
         * Team id
         */
        id: number;
    },
    {}>;

/**
 * Create team request
 */
export type CreateTeamAction = ActionDescriptor<typeof CREATE_TEAM,
    {
        /**
         * Team name
         */
        name: string;
        /**
         * Array of invite emails
         */
        invites?: string[];
    }, {
        /**
         * Created Team info
         */
        team: FullTeamInfo;
        /**
         * New members linked to invites
         */
        members: BasicUserInformation[];
    }>;

export type ChangeTeamNameAction = ActionDescriptor<typeof CHANGE_TEAM_NAME,
    {
        /**
         * Team id
         */
        id: number;
        /**
         * Team new name
         */
        name: string;
    }, {}>;

/**
 * Leave team request
 */
export type LeaveTeamAction = ActionDescriptor<typeof LEAVE_TEAM,
    {
        id: number;
    }, {}>;

export type CheckTeamCodeAction = ActionDescriptor<typeof CHECK_TEAM_CODE,
    {
        /**
         * Team code
         */
        code: string;
    }, {}>;

export type AddTeamCodeAction = ActionDescriptor<typeof ADD_TEAM_CODE,
    {
        /**
         * Team id
         */
        teamId: number;
        /**
         * Code type
         */
        type: "autogenerated";
    } | {
        /**
         * Team code
         */
        code: string;
        /**
         * Team id
         */
        teamId: number;
        /**
         * Team code
         */
        type: "custom";

    }, {
        /**
         * Autogenerated code if requested autogenerated type
         */
        code?: string;
    }>;

export type DeleteTeamCodeAction = ActionDescriptor<typeof DELETE_TEAM_CODE,
    {
        /**
         * Team code
         */
        code: string;
        /**
         * Team id
         */
        teamId: number;
    }, {}>;

export type UpdateBlacklistAction = ActionDescriptor<typeof UPDATE_BLACKLIST,
    {
        teamId: number;
        blacklist: Array<{ type: "email"; value: string }>;
    }, {}>;

export type UpdateTeamSettingsAction = ActionDescriptor<typeof UPDATE_TEAM_SETTINGS,
    {
        teamId: number;
        settings: TeamSettings;
    }, {}>;

export type TeamActions =
    DeleteTeamAction |
    CreateTeamAction |
    ChangeTeamNameAction |
    LeaveTeamAction |
    AddTeamCodeAction |
    CheckTeamCodeAction |
    DeleteTeamCodeAction |
    UpdateBlacklistAction |
    UpdateTeamSettingsAction |
    GetTeamAction |
    SetTeamDNDAction;
