import { ThemeDefinition } from "../theme";

/**
 * Team role
 */
export type TeamRole = "owner" | "admin" | "agent";

/**
 * Team type
 */
export type TeamType = "free" | "premium";

export interface TeamCode {
    /**
     * Code
     */
    code: string;
    /**
     * Code type. Custom is user provided
     */
    type: "autogenerated" | "custom";
}

export interface TeamBillingInfo {
    /**
     * Team billing email
     */
    billingEmail: string;
    /**
     * Last 4 digits for assigned card
     */
    cardDigits?: string | null;
}

/**
 * Team role -> member mapping
 */
export interface TeamMemberInfo {
    /**
     * Team id
     */
    teamId: number;
    /**
     * Member id
     */
    memberId: number;
    /**
     * Team role
     */
    role: TeamRole;
}

/**
 * Invite information
 */
export interface TeamInviteInfo {
    /**
     * Invite code
     */
    code: string;
    /**
     * Invite email
     */
    email: string;
    /**
     * Linked team to this invite
     */
    teamId: number;
    /**
     * User id if invite was linked with existing user, otherwise undefined
     */
    userId?: number;
}

export interface TeamBlacklist {
    /**
     * Blacklist value type
     */
    type: "email";
    /**
     * Blacklist value
     */
    value: string;
}

export interface TeamSettings {
    /**
     * Team data providers
     */
    dataProviders: {
        /**
         * System data provider
         */
        system: boolean;
        /**
         * IP Location data provider
         */
        ipLocation: boolean;
        /**
         * Full contact data provider
         */
        fullContact: {
            demographics: boolean;
            business: boolean;
            social: boolean;
            locations: boolean;
            education: boolean;
            topics: boolean;
        };
    };
}

export interface PartialTeamInfo {
    /**
     * Team id
     */
    id: number;
    /**
     * Team name
     */
    name: string;
    /**
     * User team role
     */
    role: TeamRole;
    /**
     * User DND flag for this team
     */
    dnd: boolean;
    /**
     * Team type
     */
    type: TeamType;
    /**
     * Team codes
     */
    codes: TeamCode[];
    /**
     * Team members
     */
    members: TeamMemberInfo[];
}

/**
 * Basic team information
 */
export interface FullTeamInfo extends PartialTeamInfo {

    /**
     * Team invites
     */
    invites: TeamInviteInfo[];

    /**
     * Premium renewal enable
     */
    premiumRenewalEnabled: boolean;

    /**
     * Premium expiration date when team type is premium
     */
    premiumExpiration?: string;

    /**
     * Team billing information. May be undefined if not assigned
     */
    billingInfo?: TeamBillingInfo;

    /**
     * Team blacklist if set
     */
    blacklist: TeamBlacklist[];

    /**
     * Team settings
     */
    settings: TeamSettings;

    /**
     * Current team theme id
     */
    currentThemeId: number;
    /**
     * Team themes
     */
    themes: ThemeDefinition[];
}
